In [1]:


import numpy as np


In [12]:
# some out of bounds performance
from scipy.constants import speed_of_light
from scipy.special import jn_zeros

diameter = 78.5e-3
length = 20.e-3


def frequency(root, q):
    cut_off = root / (np.pi * diameter)
    resoncace = q / length
    radical = cut_off * cut_off + resoncace * resoncace * 0.25
    return speed_of_light * np.sqrt(radical) * 1e-9


print(speed_of_light)
roots = np.arange(10)
excitations = np.arange(10)
frequencies = np.zeros((len(roots), len(roots), len(excitations)))
indices = np.empty((len(roots), len(roots), len(excitations)), dtype=tuple)
for m in roots:
    zeros = jn_zeros(m, 10)
    for idx, zero in enumerate(zeros):
        for q in excitations:
            f = frequency(zero, q)
            # print(f"m={m}; n={idx + 1} q={q}; f={f:.4f} GHz")
            frequencies[m, idx, q] = f
            indices[m, idx, q] = (int(m), idx, int(q))

# effective_indices = indices.reshape((1000, 3))
effective_indices = indices.reshape((1000,))
# print(effective_indices)
# print(frequencies[(0, 0, 0)])
sort_indices = np.argsort(frequencies, axis=None)
effective_sorted_indices = np.array(effective_indices[sort_indices])
# print(effective_indices[sort_indices])
# print("Now the sorted frequencies:")
# print(np.allclose(frequencies.flatten()[sort_indices], np.sort(frequencies, axis=None)))
sorted_frequencies = np.array([frequencies[idx] for idx in effective_sorted_indices])
# print(np.allclose(sorted_frequencies.flatten(), np.sort(frequencies, axis=None)))
for idx in effective_sorted_indices:
    print(f"For the mode {idx} the frequency is {frequencies[idx]:.4f} GHz")

299792458.0
For the mode (0, 0, 0) the frequency is 2.9234 GHz
For the mode (1, 0, 0) the frequency is 4.6579 GHz
For the mode (2, 0, 0) the frequency is 6.2430 GHz
For the mode (0, 1, 0) the frequency is 6.7104 GHz
For the mode (3, 0, 0) the frequency is 7.7559 GHz
For the mode (0, 0, 1) the frequency is 8.0448 GHz
For the mode (1, 1, 0) the frequency is 8.5284 GHz
For the mode (1, 0, 1) the frequency is 8.8243 GHz
For the mode (4, 0, 0) the frequency is 9.2246 GHz
For the mode (2, 0, 1) the frequency is 9.7544 GHz
For the mode (0, 1, 1) the frequency is 10.0599 GHz
For the mode (2, 1, 0) the frequency is 10.2322 GHz
For the mode (0, 2, 0) the frequency is 10.5197 GHz
For the mode (5, 0, 0) the frequency is 10.6629 GHz
For the mode (3, 0, 1) the frequency is 10.7855 GHz
For the mode (1, 1, 1) the frequency is 11.3536 GHz
For the mode (3, 1, 0) the frequency is 11.8658 GHz
For the mode (4, 0, 1) the frequency is 11.8855 GHz
For the mode (6, 0, 0) the frequency is 12.0786 GHz
For the mo

In [14]:
from scipy.special import jnp_zeros as jpn_zeros

roots = np.arange(10)
excitations = np.arange(10)
frequencies = np.zeros((len(roots), len(roots), len(excitations)))
indices = np.empty((len(roots), len(roots), len(excitations)), dtype=tuple)
for m in roots:
    zeros = jpn_zeros(m, 10)
    for idx, zero in enumerate(zeros):
        for q in excitations:
            f = frequency(zero, q)
            # print(f"m={m}; n={idx + 1} q={q}; f={f:.4f} GHz")
            frequencies[m, idx, q] = f
            indices[m, idx, q] = (int(m), idx, int(q))

effective_indices = indices.reshape((1000,))
sort_indices = np.argsort(frequencies, axis=None)
effective_sorted_indices = np.array(effective_indices[sort_indices])
sorted_frequencies = np.array([frequencies[idx] for idx in effective_sorted_indices])
for idx in effective_sorted_indices:
    print(f"For the mode {idx} the frequency is {frequencies[idx]:.4f} GHz")

For the mode (1, 0, 0) the frequency is 2.2382 GHz
For the mode (2, 0, 0) the frequency is 3.7128 GHz
For the mode (0, 0, 0) the frequency is 4.6579 GHz
For the mode (3, 0, 0) the frequency is 5.1071 GHz
For the mode (4, 0, 0) the frequency is 6.4642 GHz
For the mode (1, 1, 0) the frequency is 6.4811 GHz
For the mode (5, 0, 0) the frequency is 7.7990 GHz
For the mode (1, 0, 1) the frequency is 7.8219 GHz
For the mode (2, 1, 0) the frequency is 8.1522 GHz
For the mode (2, 0, 1) the frequency is 8.3640 GHz
For the mode (0, 1, 0) the frequency is 8.5284 GHz
For the mode (0, 0, 1) the frequency is 8.8243 GHz
For the mode (3, 0, 1) the frequency is 9.0694 GHz
For the mode (6, 0, 0) the frequency is 9.1188 GHz
For the mode (3, 1, 0) the frequency is 9.7436 GHz
For the mode (4, 0, 1) the frequency is 9.8974 GHz
For the mode (1, 1, 1) the frequency is 9.9084 GHz
For the mode (1, 2, 0) the frequency is 10.3770 GHz
For the mode (7, 0, 0) the frequency is 10.4275 GHz
For the mode (5, 0, 1) the fr

In [10]:
import iminuit
import numdifftools as nd
from optimize.optimize_test import TestNLL

validation_data = TestNLL(points=100, regenerate=True)
initial_guess = [1, 1, 1, 1, 1, 1]
m = iminuit.Minuit(validation_data, initial_guess, grad=nd.Gradient(validation_data),
                   hessian=nd.Hessian(validation_data))
m.migrad()
m.hesse()

Covariances just for reference:
[[ 1.18708265  0.11597939 -0.03714628 -0.10382743 -0.05370068 -0.08738824]
 [ 0.11597939  0.90537479 -0.03778024 -0.01596616 -0.14932104 -0.02585492]
 [-0.03714628 -0.03778024  0.81278938  0.1257716  -0.07866564  0.02164091]
 [-0.10382743 -0.01596616  0.1257716   0.85814833 -0.01396696 -0.1115751 ]
 [-0.05370068 -0.14932104 -0.07866564 -0.01396696  0.99658076  0.17111967]
 [-0.08738824 -0.02585492  0.02164091 -0.1115751   0.17111967  0.95930704]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0.1 0.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  2.  0. ]
 [0.  0.  0.  0.  0.  2. ]]


┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 594                        │  Nfcn = 9, Ngrad = 6, Nhessian = 3   │
│ EDM = 8.7e-05 (Goal: 0.0002)     │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Valid Minimum           │   Below EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│             Hesse ok             │         Covariance accurate          │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │   11.94   │   0.11    │            │            │         │         │       │
│ 1 │ x1   │   2.91    │   0.10    │            │            │         │         │       │
│ 2 │ x2   │   0.15    │   0.09    │            │            │         │         │       │
│ 3 │ x3   │   5.05    │   0.09    │            │            │         │         │       │
│ 4 │ x4   │   5.94    │   0.10    │            │            │         │         │       │
│ 5 │ x5   │   19.95   │   0.10    │            │            │         │         │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬─────────────────────────────────────────────────┐
│    │      x0      x1      x2      x3      x4      x5 │
├────┼─────────────────────────────────────────────────┤
│ x0 │  0.0119   0.001  -0.000  -0.001  -0.001  -0.001 │
│ x1 │   0.001 0.00905  -0.000  -0.000  -0.001  -0.000 │
│ x2 │  -0.000  -0.000 0.00813   0.001  -0.001   0.000 │
│ x3 │  -0.001  -0.000   0.001 0.00858  -0.000  -0.001 │
│ x4 │  -0.001  -0.001  -0.001  -0.000 0.00997   0.002 │
│ x5 │  -0.001  -0.000   0.000  -0.001   0.002 0.00959 │
└────┴─────────────────────────────────────────────────┘